// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDW3tN7MkjUhVFoYU6oMAHyWDluIPdYg',
    appId: '1:640453357931:web:e58339d8d744ce7a30dc2e',
    messagingSenderId: '640453357931',
    projectId: 'cattle-app-firebase',
    authDomain: 'cattle-app-firebase.firebaseapp.com',
    storageBucket: 'cattle-app-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGOruQkGXnRyZsYyoTd_YNgKUFKMVaDg',
    appId: '1:640453357931:android:a421e5160d692b5a30dc2e',
    messagingSenderId: '640453357931',
    projectId: 'cattle-app-firebase',
    storageBucket: 'cattle-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFwdEphvCzhPc7wNDN2y1jSH6gAmaR40',
    appId: '1:640453357931:ios:9861817e36bf0cab30dc2e',
    messagingSenderId: '640453357931',
    projectId: 'cattle-app-firebase',
    storageBucket: 'cattle-app-firebase.appspot.com',
    iosBundleId: 'com.example.cattleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmFwdEphvCzhPc7wNDN2y1jSH6gAmaR40',
    appId: '1:640453357931:ios:9861817e36bf0cab30dc2e',
    messagingSenderId: '640453357931',
    projectId: 'cattle-app-firebase',
    storageBucket: 'cattle-app-firebase.appspot.com',
    iosBundleId: 'com.example.cattleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtDW3tN7MkjUhVFoYU6oMAHyWDluIPdYg',
    appId: '1:640453357931:web:69948e159d47c27030dc2e',
    messagingSenderId: '640453357931',
    projectId: 'cattle-app-firebase',
    authDomain: 'cattle-app-firebase.firebaseapp.com',
    storageBucket: 'cattle-app-firebase.appspot.com',
  );

}